import type { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";
import DashboardLayout from "../../layouts/Dashboard";
import Head from "next/head";

const DashboardCreate: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Dashboard - Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

DashboardCreate.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default DashboardCreate;
